version: "3.7"

services:
  costs-app:
    build:
      args:
        user: timoffmax
        uid: 1000
      context: ./
      dockerfile: docker-compose/fpm/Dockerfile
    image: costs
    container_name: costs-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "10000:9000"
    networks:
      - costs

  costs-db:
    image: mysql:5.7
    container_name: costs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - costs

  costs-nginx:
    image: nginx:1.17-alpine
    container_name: costs-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - costs

networks:
  costs:
    driver: bridge
